/**
 * HCMC Clinic Health Check-up Packages Database
 * 
 * This file contains the mock data for the clinic's health check-up packages.
 * Data is exported as an ES6 module array of objects.
 * 
 * Properties:
 * - id (String): Unique identifier for the package
 * - name (String): Display name of the package
 * - suitableFor (String): Description of who this package is intended for
 * - price (Number): Cost of the package in THB
 * - isHighlight (Boolean, optional): Set to true to highlight this package in the UI
 * - filters (Object): Criteria used for searching and filtering packages
 *   - gender (String): "male" | "female" | "all"
 *   - ageGroup (String): "under-45" | "50-59" | "60-69" | etc.
 *   - hasDiabetes (Boolean): Filter condition for diabetes status
 * - items (Array of Strings): List of test items included in the package
 */

export const packages = [
  {
    id: "M40-NO-DM",
    name: "Check Up program M40 No DM",
    suitableFor: "Suitable for Non-Diabetic Male over 40-49",
    price: 5995.00,
    filters: {
      gender: "male",
      ageGroup: "40-49",
      hasDiabetes: false
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Calcium",
      "Ferritin",
      "Vitamin B12",
      "Alpha Fetoprotein/AFP( Liver)",
      "CarcinoEmbryonic Antigen/CEA (Colon)"
    ]
  },
  {
    id: "M50-NO-DM",
    name: "Check Up program M50 No DM",
    suitableFor: "Suitable for Non-Diabetic Male over 50-59",
    price: 7295.00,
    filters: {
      gender: "male",
      ageGroup: "50-59",
      hasDiabetes: false
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Magnesium",
      "Calcium",
      "Ferritin",
      "Vitamin B12",
      "CarcinoEmbryonic Antigen/CEA (Colon)",
      "Alpha Fetoprotein/AFP( Liver)",
      "PSA",
      "Testosterone"
    ]
  },
  {
    id: "M70-NO-DM",
    name: "Check Up program M70 No DM",
    suitableFor: "Suitable for Non-Diabetic Male over 70-79",
    price: 8495.00,
    filters: {
      gender: "male",
      ageGroup: "70+",
      hasDiabetes: false
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Magnesium",
      "Calcium",
      "Ferritin",
      "Vitamin B12",
      "Vitamin D",
      "CarcinoEmbryonic Antigen/CEA (Colon)",
      "Alpha Fetoprotein/AFP( Liver)",
      "CA19-9",
      "PSA",
      "Testosterone"
    ]
  },
  {
    id: "M60-NO-DM",
    name: "Check Up program M60 No DM",
    suitableFor: "Suitable for Non-Diabetic Male over 60-69",
    price: 7425.00,
    filters: {
      gender: "male",
      ageGroup: "60-69",
      hasDiabetes: false
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Magnesium",
      "Calcium",
      "Ferritin",
      "Vitamin B12",
      "CarcinoEmbryonic Antigen/CEA (Colon)",
      "Alpha Fetoprotein/AFP( Liver)",
      "CA19-9",
      "PSA",
      "Testosterone"
    ]
  },
  {
    id: "F50-DM",
    name: "Check Up program F50 DM",
    suitableFor: "Suitable for Diabetic Female over 50-59",
    price: 6925.00,
    filters: {
      gender: "female",
      ageGroup: "50-59",
      hasDiabetes: true
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "HbA1C",
      "C- reactive Protein",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Urine microalbumin",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Magnesium",
      "Calcium",
      "Ferritin",
      "Serum iron",
      "Vitamin B12",
      "CarcinoEmbryonic Antigen/CEA (Colon)",
      "Alpha Fetoprotein/AFP( Liver)"
    ]
  },
  {
    id: "METABOLIC-FU45",
    name: "Check Up - Female Under 45 with Metabolic disorder",
    suitableFor: "Suitable for Female Under 45 with Metabolic disorder",
    price: 4717.00,
    isHighlight: true, // ไฮไลท์เป็นตัวเริ่มต้นในหน้าเว็บ
    filters: {
      gender: "female",
      ageGroup: "under-40",
      hasDiabetes: false
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Blood Sugar (Fasting Blood Glucose)",
      "HbA1C (Glycated Hemoglobin)",
      "Insulin (Fasting)",
      "HOMA-IR Score (Insulin Resistance Status)",
      "C-reactive Protein (Vascular Inflammation)",
      "Lipid Panel (Cholesterol, Triglyceride, HDL, Direct LDL)",
      "Liver Function Test (AST, ALT)",
      "Urine Analysis (Proteinuria Mapping)",
      "Thyroid Function Test (TSH)"
    ]
  },
  {
    id: "METABOLIC-FO45",
    name: "Check Up - Female Over 45 with Metabolic disorder",
    suitableFor: "Suitable for Female Over 45 with Metabolic disorder",
    price: 5267.00, // แยกราคาจริงตามใบโบรชัวร์กลุ่มผู้หญิงอายุ 45+
    filters: {
      gender: "female",
      ageGroup: "50-59",
      hasDiabetes: false
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Blood Sugar (Fasting Blood Glucose)",
      "HbA1C (Glycated Hemoglobin)",
      "Insulin (Fasting)",
      "HOMA-IR Score (Insulin Resistance Status)",
      "C-reactive Protein (Vascular Inflammation)",
      "Lipid Panel (Cholesterol, Triglyceride, HDL, Direct LDL)",
      "Liver Function Test (AST, ALT)",
      "Urine Analysis (Proteinuria Mapping)",
      "Thyroid Function Test (TSH)",
      "Estradiol (E2) - Menopause & Estrogen Tracking",
      "FSH (Follicle Stimulating Hormone)"
    ]
  },
  {
    id: "METABOLIC-MALE",
    name: "Check Up - Men with Metabolic disorder",
    suitableFor: "Suitable for Men of all ages with Metabolic disorder",
    price: 5367.00, // แยกราคาจริงตามใบโบรชัวร์กลุ่มผู้ชาย
    filters: {
      gender: "male",
      ageGroup: "all",
      hasDiabetes: false
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Blood Sugar (Fasting Blood Glucose)",
      "HbA1C (Glycated Hemoglobin)",
      "Insulin (Fasting)",
      "HOMA-IR Score (Insulin Resistance Status)",
      "C-reactive Protein (Vascular Inflammation)",
      "Lipid Panel (Cholesterol, Triglyceride, HDL, Direct LDL)",
      "Liver Function Test (AST, ALT)",
      "Urine Analysis (Proteinuria Mapping)",
      "Thyroid Function Test (TSH)",
      "Total Testosterone (Male Vitality & Androgen Panel)",
      "PSA (Prostate Specific Antigen Screen)"
    ]
  },
  {
    id: "UNDER-40",
    name: "Check Up program for under 40",
    suitableFor: "Suitable for Individual under 40 yrs of age",
    price: 4270.00,
    filters: {
      gender: "all",
      ageGroup: "under-40",
      hasDiabetes: false
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "TSH",
      "Free T4",
      "Potassium",
      "Calcium",
      "Ferritin",
      "Serum iron",
      "HBs Ab",
      "HBs Ag",
      "Vitamin B12"
    ]
  },
  {
    id: "F40-DM",
    name: "Check Up program F40 DM",
    suitableFor: "Suitable for Diabetic Female over 40-49",
    price: 6650.00,
    filters: {
      gender: "female",
      ageGroup: "40-49",
      hasDiabetes: true
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "HbA1C",
      "C- reactive Protein",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Urine microalbumin",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Calcium",
      "Ferritin",
      "Serum iron",
      "Vitamin B12",
      "Alpha Fetoprotein/AFP( Liver)",
      "CarcinoEmbryonic Antigen/CEA (Colon)"
    ]
  },
  {
    id: "F60-DM",
    name: "Check Up program F60 DM",
    suitableFor: "Suitable for Diabetic Female over 60-69",
    price: 8350.00,
    filters: {
      gender: "female",
      ageGroup: "60-69",
      hasDiabetes: true
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "HbA1C",
      "C- reactive Protein",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Urine microalbumin",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Magnesium",
      "Calcium",
      "Ferritin",
      "Serum iron",
      "Vitamin B12",
      "Alpha Fetoprotein/AFP( Liver)",
      "CarcinoEmbryonic Antigen/CEA (Colon)",
      "CA153",
      "CA19-9"
    ]
  },
  {
    id: "F70-DM",
    name: "Check Up program F70 DM",
    suitableFor: "Suitable for Diabetic Female over 70-79",
    price: 9550.00,
    filters: {
      gender: "female",
      ageGroup: "70+",
      hasDiabetes: true
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "HbA1C",
      "C- reactive Protein",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Urine microalbumin",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Magnesium",
      "Calcium",
      "Ferritin",
      "Serum iron",
      "Vitamin B12",
      "Vitamin D",
      "Alpha Fetoprotein/AFP( Liver)",
      "CarcinoEmbryonic Antigen/CEA (Colon)",
      "CA153",
      "CA19-9"
    ]
  },
  {
    id: "F40-NO-DM",
    name: "Check Up program F40 No DM",
    suitableFor: "Suitable for Non Diabetic Female over 40-49",
    price: 5030.00,
    filters: {
      gender: "female",
      ageGroup: "40-49",
      hasDiabetes: false
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Calcium",
      "Ferritin",
      "Serum iron",
      "Alpha Fetoprotein/AFP( Liver)",
      "CarcinoEmbryonic Antigen/CEA (Colon)"
    ]
  },
  {
    id: "F50-NO-DM",
    name: "Check Up program F50 No DM",
    suitableFor: "Suitable for Non Diabetic Female over 50-59",
    price: 5855.00,
    filters: {
      gender: "female",
      ageGroup: "50-59",
      hasDiabetes: false
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Magnesium",
      "Calcium",
      "Ferritin",
      "Serum iron",
      "Vitamin B12",
      "Alpha Fetoprotein/AFP( Liver)",
      "CarcinoEmbryonic Antigen/CEA (Colon)"
    ]
  },
  {
    id: "F60-NO-DM",
    name: "Check Up program F60 No DM",
    suitableFor: "Suitable for Non Diabetic Female over 60-69",
    price: 7280.00,
    filters: {
      gender: "female",
      ageGroup: "60-69",
      hasDiabetes: false
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Magnesium",
      "Calcium",
      "Ferritin",
      "Serum iron",
      "Vitamin B12",
      "Alpha Fetoprotein/AFP( Liver)",
      "CarcinoEmbryonic Antigen/CEA (Colon)",
      "CA153",
      "CA19-9"
    ]
  },
  {
    id: "F70-NO-DM",
    name: "Check Up program F70 No DM",
    suitableFor: "Suitable for Non Diabetic Female over 70-79",
    price: 8480.00,
    filters: {
      gender: "female",
      ageGroup: "70+",
      hasDiabetes: false
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Magnesium",
      "Calcium",
      "Ferritin",
      "Serum iron",
      "Vitamin B12",
      "Vitamin D",
      "Alpha Fetoprotein/AFP( Liver)",
      "CarcinoEmbryonic Antigen/CEA (Colon)",
      "CA153",
      "CA19-9"
    ]
  },
  {
    id: "M40-DM",
    name: "Check Up program M40 DM",
    suitableFor: "Suitable for Diabetic Male over 40-49",
    price: 5995.00,
    filters: {
      gender: "male",
      ageGroup: "40-49",
      hasDiabetes: true
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "HbA1C",
      "C- reactive Protein",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Urine microalbumin",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Calcium",
      "Vitamin B12",
      "Alpha Fetoprotein/AFP( Liver)",
      "CarcinoEmbryonic Antigen/CEA (Colon)"
    ]
  },
  {
    id: "M50-DM",
    name: "Check Up program M50 DM",
    suitableFor: "Suitable for Diabetic Male over 50-59",
    price: 7295.00,
    filters: {
      gender: "male",
      ageGroup: "50-59",
      hasDiabetes: true
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "HbA1C",
      "C- reactive Protein",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Urine microalbumin",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Magnesium",
      "Calcium",
      "Vitamin B12",
      "CarcinoEmbryonic Antigen/CEA (Colon)",
      "Alpha Fetoprotein/AFP( Liver)",
      "PSA",
      "Testosterone"
    ]
  },
  {
    id: "M60-DM",
    name: "Check Up program M60 DM",
    suitableFor: "Suitable for Diabetic Male over 60-69",
    price: 8495.00,
    filters: {
      gender: "male",
      ageGroup: "60-69",
      hasDiabetes: true
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "HbA1C",
      "C- reactive Protein",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Urine microalbumin",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Magnesium",
      "Calcium",
      "Ferritin",
      "Vitamin B12",
      "CarcinoEmbryonic Antigen/CEA (Colon)",
      "Alpha Fetoprotein/AFP( Liver)",
      "CA19-9",
      "PSA",
      "Testosterone"
    ]
  },
  {
    id: "M70-DM",
    name: "Check Up program M70 DM",
    suitableFor: "Suitable for Diabetic Male over 70-79",
    price: 9695.00,
    filters: {
      gender: "male",
      ageGroup: "70+",
      hasDiabetes: true
    },
    items: [
      "Complete Physical Examination",
      "BP/PR/RR/BT/Weight/Height/BMI",
      "Body composition Analysis",
      "Complete Blood Count/ CBC ESR",
      "BUN/Creatinine",
      "Blood Sugar",
      "HbA1C",
      "C- reactive Protein",
      "Uric Acid",
      "Cholesterol",
      "Triglyceride",
      "High-Density Lipoprotein/ HDL",
      "Direct LDL/Low-Density Lipoprotein",
      "VLDL",
      "AST",
      "ALT",
      "Alkaline Phosphatase",
      "Total Protein",
      "Albumin",
      "Globulin",
      "Urine Analysis",
      "Urine microalbumin",
      "Stool exam and Occult Blood",
      "Electrocardiogram/ ECG",
      "TSH",
      "Free T4",
      "Potassium",
      "Magnesium",
      "Calcium",
      "Ferritin",
      "Vitamin B12",
      "Vitamin D",
      "CarcinoEmbryonic Antigen/CEA (Colon)",
      "Alpha Fetoprotein/AFP( Liver)",
      "CA19-9",
      "PSA",
      "Testosterone"
    ]
  }
];

export default packages;